# Generated by Django 5.0b1 on 2023-11-14 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(default=None, max_length=100, null=True)),
                ('store', models.CharField(default=None, max_length=100, null=True)),
                ('category', models.CharField(default=None, max_length=100, null=True)),
                ('gluten_free', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2023, 11, 14, 14, 55, 53, 66623))),
            ],
        ),
    ]
